// Generated by tools/gfxfont.py -- do not edit.
//
// The faces the screens draw with, each one GNU FreeFont covering
// Latin, Greek, Cyrillic and the punctuation those two bring. What a
// face is made of, and why it is several GFXfonts, is in src/text.h.

#pragma once

#include "text.h"

extern const TextFace fontFreeSansBold24;
extern const TextFace fontFreeSans24;
extern const TextFace fontFreeSans18;
extern const TextFace fontFreeSans12;
extern const TextFace fontFreeSansBold12;
