#include "sticky/screen.h"

#include <stdio.h>
#include <esp_attr.h>
#include "silent_mode.h"
#include "silent_icon.h"
#include "notebook_icon.h"
#include "sticky/power.h"

#include "fonts/fonts.h"
#include "sticky/epaper.h"
#include "text.h"

namespace {
// Only trusted after a completed refresh and a deep-sleep wake. No framebuffer
// survives sleep; the boolean regenerates this reserved, byte-aligned rectangle.
RTC_DATA_ATTR bool indicatorKnown = false;
RTC_DATA_ATTR bool indicatorSilent = false;

// Five faces, and the reason for each. All are GNU FreeFont, the same
// design Seeed_GFX2 bundles as GFXFF headers -- regenerated by
// tools/gfxfont.py with Greek and Cyrillic in them, which is the whole of the
// change. The Latin they draw is the Latin the device drew before.
//
// The panel is 235 dpi, so 24 pt lands at about 6 mm of line height and 18 pt
// at about 4.5 mm -- the first is a headline at arm's length, the second is
// subordinate to it without being small.
//
//  * kWordFace, at kWordSize, is the one word of listening() and working():
//    516 px of "LISTENING" on an 800 px panel, which is the largest of the
//    three by a long way because it is the screen read from across a room.
//    "WORKING" is narrower and sits in the same band, which is the point of
//    the band.
//  * kWordFace at size 1 is an error title, white inside the bar. The widest
//    in the vision's table is NO MICROPHONE at 416 px, so every title clears
//    the bar's edges with room to spare.
//  * kAnswerFace is the answer, and kDetailFace whatever narrows an error
//    down. kBatteryFace is the smaller 12 pt percentage label.
const TextFace& kWordFace = fontFreeSansBold24;
const TextFace& kAnswerFace = fontFreeSans24;
const TextFace& kDetailFace = fontFreeSans18;
const TextFace& kBatteryFace = fontFreeSansBold12;

// The word of listening() and working() is the one thing drawn at anything
// other than the face's own size.
constexpr uint8_t kWordSize = 2;

// The answer's margins, and with them the box it is wrapped into: the width
// is what a line breaks against and the height is how many lines there is
// room for. Equal on all four sides, because the block is centred inside the
// box and an answer of one line should sit where the answer of one line used
// to.
constexpr int32_t kAnswerMarginX = 40;
constexpr int32_t kAnswerMarginY = 40;

// Added above and below the face's box to make the band working() refreshes.
// It buys back the rounding in the centring arithmetic and a few pixels of
// slack, and every pixel of it is rows the controller has to be sent, so it
// is small on purpose.
constexpr int32_t kWordBandMargin = 12;

// The error bar: full width, centred vertically, with the detail under it. A
// band of black is what tells an error from an answer at a glance, before
// either has been read.
constexpr int32_t kErrorBarHeight = 130;
constexpr int32_t kErrorDetailGap = 46;

}  // namespace

bool StickyScreen::begin() {
  if (_ready) return true;

  if (!_display.begin<Board_reTerminal_Sticky, Config_Sticky_SSD1677_Fixed>()) {
    _lastError = _display.lastResult().message;
    return false;
  }

  // Landscape with the buttons along the top edge.
  _display.setRotation(2);

  if (!stickyPower::wokeFromDeepSleep()) indicatorKnown = false;
  _ready = true;
  return true;
}

void StickyScreen::startFrame() {
  indicatorKnown = false;
  _display.fillScreen(TFT_WHITE);
  _display.setTextColor(TFT_BLACK);  // one argument: no background fill
  _display.setTextSize(1);
  drawBattery();
  drawClimate();
  drawSilent(silentMode::enabled());
}

void StickyScreen::drawSilent(bool enabled) {
  silentIcon::draw(_display, enabled);
}

void StickyScreen::rememberIndicator() {
  indicatorKnown = _display.lastResult().ok();
  if (indicatorKnown) indicatorSilent = silentMode::enabled();
}

bool StickyScreen::silentIndicator() {
  if (!_ready) return false;
  const bool known = indicatorKnown;
  const bool previous = indicatorSilent;
  indicatorKnown = false;  // a reset or timeout must not bless a half-drawn icon
  if (!known) {
    clear();
    startFrame();
    _display.refresh();
    _drewFullFrame = true;
    _lastWasPartial = false;
  } else {
    drawSilent(previous);
    auto* driver = static_cast<Driver_SSD1677_Sticky*>(_display.driverPtr());
    if (!driver->beginShadowPrime()) {
      _lastError = "no memory for the previous indicator";
      return false;
    }
    // Reuse the panel's rotation, byte alignment and mirror code. The driver
    // captures its output into the shadow without driving the glass.
    const auto prime = _display.refreshPartial(
        silentIcon::kX, silentIcon::kY, silentIcon::kWidth, silentIcon::kHeight);
    driver->endShadowPrime();
    if (!prime.ok()) {
      _lastError = prime.message;
      return false;
    }
    drawSilent(silentMode::enabled());
    const auto result = _display.refreshPartial(
        silentIcon::kX, silentIcon::kY, silentIcon::kWidth, silentIcon::kHeight);
    _lastWasPartial = result.ok();
    if (!result.ok()) {
      _lastError = result.message;
      return false;
    }
  }
  rememberIndicator();
  if (!indicatorKnown) _lastError = _display.lastResult().message;
  return indicatorKnown;
}

void StickyScreen::drawBattery() {
  // Fits in the existing top margin, leaving all seven answer lines intact.
  constexpr int x = 16, y = 12, width = 42, height = 24;
  _display.fillRect(x, y, width, height, TFT_BLACK);
  _display.fillRect(x + 2, y + 2, width - 4, height - 4, TFT_WHITE);
  _display.fillRect(x + width, y + 7, 4, 10, TFT_BLACK);
  const bool valid = _batteryPercent >= 0 && _batteryPercent <= 100;
  if (valid && _batteryPercent > 0) {
    const int fill = ((width - 8) * _batteryPercent + 99) / 100;
    _display.fillRect(x + 4, y + 4, fill, height - 8, TFT_BLACK);
  }
  char label[8] = "?";
  if (valid) snprintf(label, sizeof(label), "%d%%", _batteryPercent);
  textDraw(_display, kBatteryFace, label, x + width + 14,
           y + (height - textBoxHeight(kBatteryFace, 1)) / 2, 1);
}

void StickyScreen::drawClimate() {
  char label[48] = "--°  --%";
  if (_climate.valid) {
    snprintf(label, sizeof(label), "%.1f°  %.1f%%",
             _climate.temperatureC, _climate.humidityPercent);
  }
  textDraw(_display, kBatteryFace, label,
           _display.width() - 16 - textWidth(kBatteryFace, label, 1),
           12 + (24 - textBoxHeight(kBatteryFace, 1)) / 2, 1);
}

void StickyScreen::drawCentred(const TextFace& face, const char* text,
                               int32_t centreX, int32_t middleY, uint8_t size) {
  const int32_t width = textWidth(face, text, size);
  const int32_t height = textBoxHeight(face, size);
  textDraw(_display, face, text, centreX - width / 2, middleY - height / 2, size);
}

void StickyScreen::clear() {
  if (!_ready) return;
  indicatorKnown = false;

  _display.fillScreen(TFT_WHITE);
  _display.refresh();
  _drewFullFrame = true;
  _lastWasPartial = false;
}

void StickyScreen::refreshWhole() {
  // A full refresh has to have run this boot, or the shadow the partial is
  // differential against is the all-white one a fresh allocation starts as
  // while the glass still holds the last question's answer.
  if (_drewFullFrame && _display.refreshPartial(0, 0, _display.width(), _display.height()).ok()) {
    _lastWasPartial = true;
    rememberIndicator();
    return;
  }

  if (_drewFullFrame) _lastError = _display.lastResult().message;
  _display.refresh();
  _drewFullFrame = true;
  _lastWasPartial = false;
  rememberIndicator();
}

void StickyScreen::wordBand(int32_t& y, int32_t& height) {
  height = textBoxHeight(kWordFace, kWordSize) + 2 * kWordBandMargin;
  y = (_display.height() - height) / 2;
}

void StickyScreen::idle() {
  if (!_ready) return;
  startFrame();
  notebookIcon::draw(_display);
  refreshWhole();
}

void StickyScreen::listening() {
  if (!_ready) return;

  startFrame();
  drawCentred(kWordFace, "LISTENING", _display.width() / 2, _display.height() / 2,
              kWordSize);
  _display.refresh();
  _drewFullFrame = true;
  _lastWasPartial = false;
  rememberIndicator();
}

bool StickyScreen::working() {
  if (!_ready) return false;

  int32_t y = 0;
  int32_t height = 0;
  wordBand(y, height);

  // The frame buffer outside the band is left exactly as listening() drew it,
  // because it is exactly what is on the glass and the partial refresh will not
  // send it. Only the band is repainted, and only the band is pushed.
  _display.setTextColor(TFT_BLACK);
  _display.fillRect(0, y, _display.width(), height, TFT_WHITE);
  drawCentred(kWordFace, "WORKING", _display.width() / 2, _display.height() / 2,
              kWordSize);

  const GfxResult result = _display.refreshPartial(0, y, _display.width(), height);
  _lastWasPartial = result.ok();
  if (!result.ok()) {
    _lastError = result.message;
    return false;
  }
  return true;
}

void StickyScreen::answer(const char* text) {
  if (!_ready) return;

  startFrame();

  const int32_t boxWidth = _display.width() - 2 * kAnswerMarginX;
  const int32_t boxHeight = _display.height() - 2 * kAnswerMarginY;
  const int32_t lineBox = textBoxHeight(kAnswerFace, 1);
  const int32_t lineHeight = kAnswerFace.yAdvance;

  // N lines are (N - 1) gaps and one box tall, not N boxes: the last line has
  // nothing under it to be spaced from.
  const int32_t maxLines = (boxHeight - lineBox) / lineHeight + 1;
  const int32_t wanted = textWrapLines(kAnswerFace, text, 1, boxWidth);
  const int32_t lines = wanted < maxLines ? wanted : maxLines;

  if (lines > 0) {
    // Centred as a block, so a one-line answer sits where a one-line answer
    // has always sat and a five-line one grows evenly around it.
    const int32_t top = (_display.height() - ((lines - 1) * lineHeight + lineBox)) / 2;
    textDrawWrapped(_display, kAnswerFace, text, kAnswerMarginX, top, 1, boxWidth, maxLines);
  }

  refreshWhole();
}

void StickyScreen::error(const char* title, const char* detail) {
  if (!_ready) return;

  const int32_t barY = (_display.height() - kErrorBarHeight) / 2;

  startFrame();
  _display.fillRect(0, barY, _display.width(), kErrorBarHeight, TFT_BLACK);

  _display.setTextColor(TFT_WHITE);
  drawCentred(kWordFace, title, _display.width() / 2, barY + kErrorBarHeight / 2, 1);

  if (detail != nullptr && detail[0] != '\0') {
    _display.setTextColor(TFT_BLACK);
    const int32_t width = textWidth(kDetailFace, detail, 1);
    textDraw(_display, kDetailFace, detail, (_display.width() - width) / 2,
             barY + kErrorBarHeight + kErrorDetailGap, 1);
  }

  refreshWhole();
}
