#pragma once

#include <Seeed_GFX.h>

#include <stddef.h>
#include <stdint.h>

// Laying a UTF-8 string out in a face made of several GFXfonts.
//
// This is what D1 turned into. The panel draws Latin, Greek and Cyrillic
// because src/fonts/ holds those glyphs, and it lays them out here because
// Seeed_GFX2 cannot: two things in the library stand in the way, and both are
// in code that cannot be subclassed around.
//
//  * **A GFXfont is one contiguous range.** `first` and `last` are uint16_t,
//    so the format reaches Cyrillic in principle -- but it has no way to
//    express a hole, and our code points are mostly hole: Latin ends at
//    0x7E, Cyrillic starts at 0x401, the numero sign sits alone at 0x2116.
//    One range from 0x20 to 0x2116 would be 8455 glyph descriptors, 67 KiB
//    per face, for about 250 glyphs. So a face here is several GFXfonts, each
//    tight around one script, and textDraw() picks between them per
//    character. That costs 2.3 KiB of descriptors per face instead, and no
//    code point is anywhere but at its own value.
//
//  * **Seeed_GFX2::textWidth() reads bytes, not characters.** Its GFXFF
//    branch is `uniCode = *(string++)`, with no decodeUTF8 -- so every
//    multi-byte character falls outside the font's range and adds nothing,
//    and a Cyrillic string measures as empty. drawString() centres on that
//    measurement, and neither it nor textWidth() is virtual, so a subclass
//    cannot correct either. Anything centred has to be measured here and
//    drawn from a corner, which is what textWidth() and textDraw() below are
//    for. drawString() is not used by this firmware for that reason.
//
// What is still the library's is the glyph blitting: textDraw() sets the
// right GFXfont and calls Seeed_GFX2's own drawChar() per character.
//
// Nothing here knows about the panel. It is ordinary logic that happens to
// take a Seeed_GFX to draw on, and the measuring half does not even take
// that.

// A face is the several GFXfonts that together cover what the device draws,
// plus the box they share. Generated by tools/gfxfont.py, one per entry in
// src/fonts/fonts.h.
//
// `ascent` and `descent` are measured across every font in the face, and that
// is the point of keeping them here rather than asking the library: a line of
// Cyrillic and a line of Latin sit on the same baseline because both reserve
// the room Ё needs above the cap height, whether or not the line has one in
// it. The cost is that an all-Latin word sits a few pixels lower than it did
// when the face was Latin alone -- which is the right trade, because the
// alternative is a baseline that moves when the language does.
struct TextFace {
  const GFXfont* const* fonts;
  uint8_t fontCount;
  uint8_t ascent;    // top of the box to the baseline
  uint8_t descent;   // baseline to the bottom of the box
  uint8_t yAdvance;  // line to line, which is more than ascent + descent
};

// The box a single line of this face occupies at this size. Every placement
// below is in terms of it, so a caller never has to know where the baseline
// falls.
inline int32_t textBoxHeight(const TextFace& face, uint8_t size) {
  return static_cast<int32_t>(face.ascent + face.descent) * size;
}

// The next character in a UTF-8 string, with `cursor` advanced past it. Zero
// at the end of the string, and nothing else returns zero.
//
// A byte sequence that is not UTF-8 -- including one cut in half by a copy
// into a fixed buffer -- yields U+FFFD and the cursor moves on by at least
// one byte, so a malformed string always terminates and always terminates
// somewhere sane. U+FFFD is in no face, so it draws as the '?' any
// undrawable character draws as.
uint32_t textNextCodepoint(const char** cursor);

// Whether the face can draw this character as itself rather than as '?'.
bool textHasGlyph(const TextFace& face, uint32_t codepoint);

// The width of the string as textDraw() would draw it, substitutions
// included. The two share the glyph lookup, so a centred string cannot be
// measured as one thing and drawn as another.
int32_t textWidth(const TextFace& face, const char* text, uint8_t size);

// Draws the string with the top-left of its box at (x, top). Returns where
// the next character would go, which is x plus the width.
int32_t textDraw(Seeed_GFX& gfx, const TextFace& face, const char* text,
                 int32_t x, int32_t top, uint8_t size);

// The two below break a string into lines that fit `maxWidth`, which is what
// D2 turned into: an answer is a sentence or two from a model now, and one
// line of 24 pt holds about 45 characters.
//
// A line breaks at the last space that fits. A word wider than the whole line
// breaks inside itself, at the last character that fits, which is the only
// way a line can break with no space in it -- and is also what keeps a string
// with no space in it at all from looping forever. A newline in the text is a
// break of its own, so a backend that sends two sentences on two lines gets
// two lines. The spaces a line breaks at are not drawn at either end of it.

// How many lines the string takes, which a caller needs before it can place
// the first one: a block of text is centred as a block. Zero for an empty
// string, so that nothing is what nothing is laid out as.
int32_t textWrapLines(const TextFace& face, const char* text, uint8_t size,
                      int32_t maxWidth);

// Draws the string as lines, the first line's box top-left at (x, top) and
// each line after it one yAdvance lower. Returns how many were drawn.
//
// `maxLines` is the panel rather than the string: at most that many are drawn,
// and if the string has more to say than that the last one ends in an
// ellipsis. Dropping the tail silently would make an answer that was cut short
// look like the whole of it, which is the one thing a screen with no scrollbar
// must not do -- and pagination, which is where D2 goes next, has to know the
// answer did not fit anyway.
int32_t textDrawWrapped(Seeed_GFX& gfx, const TextFace& face, const char* text,
                        int32_t x, int32_t top, uint8_t size, int32_t maxWidth,
                        int32_t maxLines);

// Copies a UTF-8 string into a buffer of `size` bytes, truncating on a
// character boundary rather than in the middle of one. `text` may be null,
// which gives an empty string.
//
// The bound a screen puts on what it draws is in bytes, because the buffer
// is; this is what keeps that from being a bound that can cut a letter in
// half. A truncated tail would decode as U+FFFD and draw as '?', which is not
// wrong so much as untidy -- there is no reason to show a character that was
// never in the answer.
void textCopy(char* out, size_t size, const char* text);
